name: Daily job

on:
  schedule:
    - cron: "*/5 * * * *" # daily at 12:00 AM
  # you can add more here triggers see: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
  # example, it will run every day for the `main`
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
