name: Daily job

on:
  schedule:
    - cron: "* * * * *" # daily at 12:00 AM
  # you can add more here triggers see: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
  # example, it will run every day for the `main`
  push:
      branches:
        - 'main'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I RAN EVERY MINUTE I THINK"
